### ISSUE TITLE
Catch the `workbench.files.action.showActiveFileInExplorer` to point in Go Mod Explorer

### ISSUE THREAD

**Issue by pasquale95** [r3inbowari/go-mod-explorer#61]
Hi,
thanks for the beautiful extension! 
I open this issue to understand if this functionality is already available or can be added.
Basically, if I have the file opened in VSCode and I want to move back to the project explorer, how can I do it?
In VSCode there's the command `workbench.files.action.showActiveFileInExplorer` which allows to point to the opened file inside the project explorer.
However, when I perform such operation on a file belonging to a Go external lib, I'm not redirected inside the *Go Mod Explorer*, but in the *Open Editors* section.
Is there a way (or a condition) I could use to redirect the action to show the file inside the Go Mod Explorer?

**Comment by r3inbowari** [comment]
Hi, @pasquale95, Right, I will see whether we can do it this weekend.

**Comment by r3inbowari** [comment]
As you see here, the build-in method ShowActiveFileInExplorer is implemented in vscode [snippet1: REVEAL_IN_EXPLORER command](https://github.com/microsoft/vscode/blob/b2864137d08dd3d9fef3a7c2f4d1b4b023a803dc/src/vs/workbench/contrib/files/browser/fileCommands.ts#L321) and [snippet2: Action](https://github.com/microsoft/vscode/blob/b2864137d08dd3d9fef3a7c2f4d1b4b023a803dc/src/vs/workbench/contrib/files/browser/fileActions.ts#L628C14-L628C39). They specify two branches, the object is either opened in the workspace view or in the editor view. We have no way to reuse this method to perform reveal operations in Go Mod Explorer view. Because when we have the same keybinding , only one to be executed correctly.

So, we should create a new different keybinding for it, @pasquale95, what do you think?
`Ctrl(⌘) + Shift + "` or?

**Comment by pasquale95** [comment]
I think we should just give create a new action and give people the possibility to choose which keybinding to associate with.
As a predefined one, yours would be okay.

**Comment by r3inbowari** [comment]
Hi, @pasquale95. I think this issue has been resolved, Please upgrade to `v0.3.12`.

**Comment by r3inbowari** [comment]
Also I noticed the [fork](https://github.com/vsr625/go-mod-explorer/commit/27ab6e33278a61d9e91dcff3ed89fbc4f0897d8a) by @vsr625, this feature(reveal without focusing) is also supported now. Thanks for pointing out.
